### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by LivingSacrifice121** [blxstealer/BLX-Stealer#20]
When i try to open the exe file that was created I get an error 
![image](https://github.com/blxstealer/BLX-Stealer/assets/149721896/8fad37bd-6b8d-41cb-86aa-0aa7c7fa18d7)

**Comment by blxstealer** [comment]
Open a CMD then write;
pip install browser_cookie3

**Comment by LivingSacrifice121** [comment]
Now i get this 
![image](https://github.com/blxstealer/BLX-Stealer/assets/149721896/f4dd99e9-b04f-40d0-a748-a585957a7d53)

**Comment by blxstealer** [comment]
You can reinstall Python. I recommend 3.10.2 👍

**Comment by LivingSacrifice121** [comment]
thank u it worked
